### ISSUE TITLE
[Question]how to get a bool mask?

### ISSUE THREAD

**Issue by JSHZT** [andres-fr/face_segmentation_pytorch#3]
Thanks for your work, I can stay away from the pain of configuring caffe, but I am still confused in the process of using it. What is the meaning of the 'out' variable output by the code example in the readme? I want to get a bool type mask, only this That's all

**Comment by andres-fr** [comment]
Hi, I'm glad it helped! The 4th sentence of the README->Usage section gives instructions to create the mask.
Edit: if you are using python, change the `as_pmap` variable to `False`.

 Let me know if you have any issues with that, otherwise I will close this issue. Cheers
